package com.example.aftas_back.domain.enums;

public enum PermissionType {
    VIEW_COMPETITIONS, CREATE_COMPETITIONS, UPDATE_COMPETITIONS, DELETE_COMPETITIONS,
    VIEW_USERS, CREATE_USERS, UPDATE_USERS, DELETE_USERS,
    VIEW_RANKING, CREATE_RANKING, UPDATE_RANKING, DELETE_RANKING,
    VIEW_HUNTING, CREATE_HUNTING, UPDATE_HUNTING, DELETE_HUNTING,
    VIEW_FISHES, CREATE_FISHES, UPDATE_FISHES, DELETE_FISHES,
    VIEW_LEVEL, CREATE_LEVEL, UPDATE_LEVEL, DELETE_LEVEL
}
